### ISSUE TITLE
Build fails on OS X yosemite

### ISSUE THREAD

**Issue by PietaSchofield** [vcflib/vcflib#85]
Hullo 

I am trying to build on OS X and I get the following error 

darwin: make
cd tabixpp && /Applications/Xcode.app/Contents/Developer/usr/bin/make
ar -cru libtabix.a 
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
    ar -m [-TLsv] archive file ...
    ar -m [-abiTLsv] position archive file ...
    ar -p [-TLsv] archive [file ...]
    ar -q [-cTLsv] archive file ...
    ar -r [-cuTLsv] archive file ...
    ar -r [-abciuTLsv] position archive file ...
    ar -t [-TLsv] archive [file ...]
    ar -x [-ouTLsv] archive [file ...]
make[2]: **\* [libtabix.a] Error 1
make[1]: **\* [all-recur] Error 1
make: **\* [tabixpp/tabix.o] Error 2

It appears to be because in the tabixpp Makefile the $(LOBJS) value is not set to anything when it tries to complete the rule libtabix.a.

Manually setting $(LOBJS) to tabix.o and removing the -s switch in the smithwaterman Makefile seems to let the make complete and produce programs that at least display their usage, but I am wondering if there are other object that should be included in LOBJS? I am also wondering why it builds ok on Linux without manually setting $LOBJS but not my OS X install.

Thanks 

Pieta

**Comment by charleshefer** [comment]
Hi
I have had the same experience as OP. Builds fine on RedHat but not on OS X. OP's changes to the respective Makefiles does the job to get the package to compile.

**Comment by nekrut** [comment]
My guess is that Pieta is doing this:

`make LOBJS=tabix.o`

Alternatively `LOBJS=tabix.o1` can be added to the beginning of Make file with tabixpp.

**Comment by PietaSchofield** [comment]
Indeed I was doing the second I added the line to the Makefile in tabixpp

LOBJS=tabix.o

after the line 

LIBPATH=-L. -Lhtslib

**Comment by pygmyperch** [comment]
I tried the changes to the two Makefiles as suggested above, but still wont compile (OSX 10.10.2) and gives the following error:

cd tabixpp && /Applications/Xcode.app/Contents/Developer/usr/bin/make
g++ -g -Wall -O2 -fPIC  -c tabix.cpp -Ihtslib
ar -cru libtabix.a tabix.o
ranlib libtabix.a
cd htslib && /Applications/Xcode.app/Contents/Developer/usr/bin/make lib-static
gcc -g -Wall -O2 -fPIC  -I.  -c -o kfunc.o kfunc.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o knetfile.o knetfile.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o kstring.o kstring.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o bgzf.o bgzf.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o faidx.o faidx.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o hfile.o hfile.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "1.2.1-29-gf83dfd2"' > version.h
gcc -g -Wall -O2 -fPIC  -I.  -c -o hts.o hts.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o regidx.o regidx.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o sam.o sam.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o synced_bcf_reader.o synced_bcf_reader.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o vcf_sweep.o vcf_sweep.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o tbx.o tbx.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o vcf.o vcf.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o vcfutils.o vcfutils.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o cram/cram_codecs.o cram/cram_codecs.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o cram/cram_decode.o cram/cram_decode.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o cram/cram_encode.o cram/cram_encode.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o cram/cram_index.o cram/cram_index.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o cram/cram_io.o cram/cram_io.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o cram/cram_samtools.o cram/cram_samtools.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o cram/cram_stats.o cram/cram_stats.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o cram/files.o cram/files.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o cram/mFILE.o cram/mFILE.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o cram/md5.o cram/md5.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o cram/open_trace_file.o cram/open_trace_file.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o cram/pooled_alloc.o cram/pooled_alloc.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o cram/rANS_static.o cram/rANS_static.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o cram/sam_header.o cram/sam_header.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o cram/string_alloc.o cram/string_alloc.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o cram/thread_pool.o cram/thread_pool.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o cram/vlen.o cram/vlen.c
gcc -g -Wall -O2 -fPIC  -I.  -c -o cram/zfio.o cram/zfio.c
ar -rc libhts.a kfunc.o knetfile.o kstring.o bgzf.o faidx.o hfile.o hfile_net.o hts.o regidx.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/md5.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/sam_header.o cram/string_alloc.o cram/thread_pool.o cram/vlen.o cram/zfio.o
ranlib libhts.a
g++ -g -Wall -O2 -fPIC  -o tabix++ main.cpp tabix.o -Ihtslib -L. -Lhtslib -lhts -lpthread -lm -lz
g++ -c -o src/Variant.o src/Variant.cpp -I. -Itabixpp/htslib/ -L. -Ltabixpp/ -Ltabixpp/htslib/ -lvcflib -ltabix -lhts -lpthread -lz -lm -O3 -D_FILE_OFFSET_BITS=64
g++ -c -o src/split.o src/split.cpp -I. -Itabixpp/htslib/ -L. -Ltabixpp/ -Ltabixpp/htslib/ -lvcflib -ltabix -lhts -lpthread -lz -lm -O3 -D_FILE_OFFSET_BITS=64
cd smithwaterman && /Applications/Xcode.app/Contents/Developer/usr/bin/make
c++    -c -o smithwaterman.o smithwaterman.cpp
smithwaterman.cpp:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^
1 error generated.
make[1]: **\* [smithwaterman.o] Error 1
make: **\* [smithwaterman/SmithWatermanGotoh.o] Error 2

anyone have any suggestions

thanks
Chris

**Comment by tseemann** [comment]
@ekg I think there are multiple issues here related to library linking: 
1. tabixpp Makefile is missing a variable: https://github.com/ekg/tabixpp/issues/5
2. smithwaterman - linker option fix: https://github.com/ekg/smithwaterman/issues/4

When I implement the above two changes, it will compile on OSX and Linux.

**Comment by tseemann** [comment]
I've managed to get it compiled and working under the Brew package manager if that helps:
https://github.com/Homebrew/homebrew-science/pull/2092

**Comment by pygmyperch** [comment]
Thanks for that, I will try and see how it goes. I have just been using a linux virtual machine for now as the two changes you mentioned above didn't seem to help.

**Comment by tseemann** [comment]
Latest homebrew build is here: https://github.com/homebrew/homebrew-science/blob/master/vcflib.rb

**Comment by zeeev** [comment]
@tseemann Master build on OS X 10.10.5.  The recent bug fixes might be worth a home-brew bump?

**Comment by tseemann** [comment]
@zeeev when we resolve the missing scripts issue (vcfsort etc.) , you should tag a new `-rc2` release and i'll update the brew package.

**Comment by zeeev** [comment]
Will do.  I'm still working on the filter issue.
