### ISSUE TITLE
__off64_t in fastahack/LargeFileSupport.h cause compilation issues

### ISSUE THREAD

**Issue by arq5x** [vcflib/vcflib#3]
Not sure why this is, but it won't compile on my Mac (gcc 4.2.1).  If I change to "typedef off_t off_type;", all is well.  

In file included from Fasta.h:19,
                 from Fasta.cpp:9:
LargeFileSupport.h:12: error: ‘__off64_t’ does not name a type
make[1]: **\* [Fasta.o] Error 1
make: **\* [fastahack/Fasta.o] Error 2

**Comment by tseemann** [comment]
Hello from the future young @arq5x !
