### ISSUE TITLE
compiling on Ubuntu 12.04 64-bit

### ISSUE THREAD

**Issue by avilella** [vcflib/vcflib#14]
I got an issue trying to compile on an Ubuntu 12.04 64-bit VM:
...
gcc -g -Wall -O2 -fPIC  -o tabix main.o -lm  -lz -L. -ltabix
./libtabix.a(bgzf.o): In function `deflate_block':
/home/avilella/src/vcflib/tabixpp/bgzf.c:311: undefined reference to`deflate'
/home/avilella/src/vcflib/tabixpp/bgzf.c:313: undefined reference to `deflateEnd'
/home/avilella/src/vcflib/tabixpp/bgzf.c:305: undefined reference to`deflateInit2_'
/home/avilella/src/vcflib/tabixpp/bgzf.c:329: undefined reference to `deflateEnd'
/home/avilella/src/vcflib/tabixpp/bgzf.c:345: undefined reference to`crc32'
/home/avilella/src/vcflib/tabixpp/bgzf.c:346: undefined reference to `crc32'
./libtabix.a(bgzf.o): In function`inflate_block':
/home/avilella/src/vcflib/tabixpp/bgzf.c:380: undefined reference to `inflateInit2_'
/home/avilella/src/vcflib/tabixpp/bgzf.c:385: undefined reference to`inflate'
/home/avilella/src/vcflib/tabixpp/bgzf.c:391: undefined reference to `inflateEnd'
/home/avilella/src/vcflib/tabixpp/bgzf.c:387: undefined reference to`inflateEnd'
./libtabix.a(bedidx.o): In function `ks_getuntil':
/home/avilella/src/vcflib/tabixpp/bedidx.c:11: undefined reference to`gzread'
./libtabix.a(bedidx.o): In function `bed_read':
/home/avilella/src/vcflib/tabixpp/bedidx.c:103: undefined reference to`gzdopen'
./libtabix.a(bedidx.o): In function `ks_getc':
/home/avilella/src/vcflib/tabixpp/bedidx.c:11: undefined reference to`gzread'
./libtabix.a(bedidx.o): In function `bed_read':
/home/avilella/src/vcflib/tabixpp/bedidx.c:138: undefined reference to`gzclose'
/home/avilella/src/vcflib/tabixpp/bedidx.c:103: undefined reference to `gzopen64'
collect2: ld returned 1 exit status
make[2]: *** [tabix] Error 1
make[2]: g++ -O3 -D_FILE_OFFSET_BITS=64   -c -o smithwaterman/IndelAllele.o smithwaterman/IndelAllele.cpp
*** Waiting for unfinished jobs....
make[2]: Leaving directory`/home/avilella/src/vcflib/tabixpp'
make[1]: **\* [all-recur] Error 1
make[1]: Leaving directory `/home/avilella/src/vcflib/tabixpp'
make: *** [tabixpp/tabix.o] Error 2
make: *** Waiting for unfinished jobs....
make[1]: Leaving directory`/home/avilella/src/vcflib/fastahack'

**Comment by avilella** [comment]
I still get an error compiling on CentOS 5 even when doing a git --recursive:

g++ -O3 -D_FILE_OFFSET_BITS=64   -c -o ssw_cpp.o ssw_cpp.cpp
cd fsom && g++ -O3 -D_FILE_OFFSET_BITS=64 -c fsom.c -lm
fsom.h:77: error: non-local function ‘void som_network_destroy(som_network_t_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.h:78: error: non-local function ‘void som_set_inputs(som_network_t_, double_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.h:79: error: non-local function ‘void som_train(som_network_t_, double**, size_t, size_t)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.h:80: error: non-local function ‘void som_serialize(som_network_t_, const char_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.h:81: error: non-local function ‘void som_init_weights(som_network_t*, double**, size_t)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.h:82: error: non-local function ‘double som_get_best_neuron_coordinates(som_network_t_, size_t_, size_t_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.h:83: error: non-local function ‘som_network_t_ som_deserialize(const char_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.h:84: error: non-local function ‘som_network_t_ som_network_new(size_t, size_t, size_t)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.c:249: error: non-local function ‘som_network_t\* som_network_new(size_t, size_t, size_t)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.c:397: error: non-local function ‘void som_network_destroy(som_network_t_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.c:417: error: non-local function ‘void som_set_inputs(som_network_t_, double_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.c:436: error: non-local function ‘double som_get_best_neuron_coordinates(som_network_t_, size_t_, size_t_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.c:560: error: non-local function ‘double som_learning_rate_fast(som_network_t_, size_t, double, size_t)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.c: In function ‘void som_train_iteration(som_network_t_, double_, size_t)’:
fsom.c:597: warning: converting to ‘size_t’ from ‘double’
fsom.c: At global scope:
fsom.c:616: error: non-local function ‘void som_init_weights(som_network_t_, double**, size_t)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.c:859: error: non-local function ‘void som_train(som_network_t*, double**, size_t, size_t)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.c:887: error: non-local function ‘void som_serialize(som_network_t_, const char_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
fsom.c:927: error: non-local function ‘som_network_t\* som_deserialize(const char_)’ uses anonymous type
fsom.h:75: error: ‘typedef struct<anonymous> som_network_t’ does not refer to the unqualified type, so it is not used for linkage
make: *_\* [fsom/fsom.o] Error 1

**Comment by gusevfe** [comment]
I think your GCC is too old. I just had the same error on a system with GCC 4.4. But it compiles OK on a system with GCC 4.8.2.

**Comment by zeeev** [comment]
@avilella is this still an issue for you?  I know the report is old, but i'm going through them.  I've setup travis for Ubuntu.
