### ISSUE TITLE
Build from source not working with zig 0.16.0

### ISSUE THREAD

**Issue by Alexandra2022kzn** [vcflib/vcflib#446]
Hello! Thank you for creating this tool!

This issue is similar to https://github.com/vcflib/vcflib/issues/399 and https://github.com/vcflib/vcflib/issues/423

I tried zig 0.16.0 and vcflib 1.0.15 and build is failing with this error:

<details>
<summary>
Build log
</summary>

```
> make
[  1%] Building CXX object CMakeFiles/vcflib.dir/src/legacy.cpp.o
[  1%] Building CXX object CMakeFiles/vcflib.dir/src/vcf-wfa.cpp.o
[  2%] Building CXX object CMakeFiles/vcflib.dir/src/vcf-c-api.cpp.o
[  2%] Building CXX object CMakeFiles/vcflib.dir/src/Variant.cpp.o
[  2%] Building CXX object CMakeFiles/vcflib.dir/src/rnglib.cpp.o
[  3%] Building CXX object CMakeFiles/vcflib.dir/src/var.cpp.o
[  3%] Building CXX object CMakeFiles/vcflib.dir/src/pdflib.cpp.o
[  4%] Building CXX object CMakeFiles/vcflib.dir/src/cdflib.cpp.o
[  4%] Building CXX object CMakeFiles/vcflib.dir/src/split.cpp.o
[  5%] Building CXX object CMakeFiles/vcflib.dir/src/stats.cpp.o
[  5%] Building CXX object CMakeFiles/vcflib.dir/src/index.cpp.o
[  6%] Building CXX object CMakeFiles/vcflib.dir/src/phase.cpp.o
[  6%] Building CXX object CMakeFiles/vcflib.dir/src/rkmh.cpp.o
[  7%] Building CXX object CMakeFiles/vcflib.dir/src/murmur3.cpp.o
[  7%] Building CXX object CMakeFiles/vcflib.dir/src/LeftAlign.cpp.o
[  7%] Building CXX object CMakeFiles/vcflib.dir/src/cigar.cpp.o
[  8%] Building CXX object CMakeFiles/vcflib.dir/src/allele.cpp.o
[  8%] Building CXX object CMakeFiles/vcflib.dir/contrib/fastahack/Fasta.cpp.o
[  9%] Building CXX object CMakeFiles/vcflib.dir/contrib/smithwaterman/SmithWatermanGotoh.cpp.o
[  9%] Building CXX object CMakeFiles/vcflib.dir/contrib/smithwaterman/Repeats.cpp.o
[ 10%] Building CXX object CMakeFiles/vcflib.dir/contrib/smithwaterman/IndelAllele.cpp.o
[ 10%] Building CXX object CMakeFiles/vcflib.dir/contrib/smithwaterman/disorder.cpp.o
[ 11%] Building CXX object CMakeFiles/vcflib.dir/contrib/smithwaterman/LeftAlign.cpp.o
[ 11%] Building C object CMakeFiles/vcflib.dir/contrib/fsom/fsom.c.o
/soft/vcflib-1.0.15-src/contrib/fsom/fsom.c: In function ‘som_deserialize’:
/soft/vcflib-1.0.15-src/contrib/fsom/fsom.c:949:9: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  949 |         fread ( &(net->serialization_time), sizeof ( time_t ), 1, fp );
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/soft/vcflib-1.0.15-src/contrib/fsom/fsom.c:950:9: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  950 |         fread ( &(net->T_learning_param ), sizeof ( double ), 1, fp );
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/soft/vcflib-1.0.15-src/contrib/fsom/fsom.c:951:9: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  951 |         fread ( &input_neurons, sizeof ( size_t ), 1, fp );
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/soft/vcflib-1.0.15-src/contrib/fsom/fsom.c:952:9: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  952 |         fread ( &output_neurons_rows, sizeof ( size_t ), 1, fp );
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/soft/vcflib-1.0.15-src/contrib/fsom/fsom.c:953:9: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  953 |         fread ( &output_neurons_cols, sizeof ( size_t ), 1, fp );
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/soft/vcflib-1.0.15-src/contrib/fsom/fsom.c:974:33: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  974 |                                 fread ( &weight, sizeof ( double ), 1, fp );
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 12%] Building C object CMakeFiles/vcflib.dir/contrib/filevercmp/filevercmp.c.o
[ 12%] Building C object CMakeFiles/vcflib.dir/contrib/c-progress-bar/progress.c.o
/soft/vcflib-1.0.15-src/contrib/c-progress-bar/progress.c: In function ‘print_timedelta’:
/soft/vcflib-1.0.15-src/contrib/c-progress-bar/progress.c:79:28: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
   79 |         fprintf(stderr,"%lluh %llum %llus    ", hours, minutes, seconds);
      |                         ~~~^                    ~~~~~
      |                            |                    |
      |                            |                    uint64_t {aka long unsigned int}
      |                            long long unsigned int
      |                         %lu
/soft/vcflib-1.0.15-src/contrib/c-progress-bar/progress.c:79:34: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
   79 |         fprintf(stderr,"%lluh %llum %llus    ", hours, minutes, seconds);
      |                               ~~~^                     ~~~~~~~
      |                                  |                     |
      |                                  |                     uint64_t {aka long unsigned int}
      |                                  long long unsigned int
      |                               %lu
/soft/vcflib-1.0.15-src/contrib/c-progress-bar/progress.c:79:40: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 5 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
   79 |         fprintf(stderr,"%lluh %llum %llus    ", hours, minutes, seconds);
      |                                     ~~~^                        ~~~~~~~
      |                                        |                        |
      |                                        long long unsigned int   uint64_t {aka long unsigned int}
      |                                     %lu
/soft/vcflib-1.0.15-src/contrib/c-progress-bar/progress.c:82:28: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
   82 |         fprintf(stderr,"%llum %02llus        ", minutes, seconds);
      |                         ~~~^                    ~~~~~~~
      |                            |                    |
      |                            |                    uint64_t {aka long unsigned int}
      |                            long long unsigned int
      |                         %lu
/soft/vcflib-1.0.15-src/contrib/c-progress-bar/progress.c:82:36: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
   82 |         fprintf(stderr,"%llum %02llus        ", minutes, seconds);
      |                               ~~~~~^                     ~~~~~~~
      |                                    |                     |
      |                                    |                     uint64_t {aka long unsigned int}
      |                                    long long unsigned int
      |                               %02lu
/soft/vcflib-1.0.15-src/contrib/c-progress-bar/progress.c:85:28: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 3 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
   85 |         fprintf(stderr,"%llu.%llus           ", seconds, mseconds);
      |                         ~~~^                    ~~~~~~~
      |                            |                    |
      |                            |                    uint64_t {aka long unsigned int}
      |                            long long unsigned int
      |                         %lu
/soft/vcflib-1.0.15-src/contrib/c-progress-bar/progress.c:85:33: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
   85 |         fprintf(stderr,"%llu.%llus           ", seconds, mseconds);
      |                              ~~~^                        ~~~~~~~~
      |                                 |                        |
      |                                 long long unsigned int   uint64_t {aka long unsigned int}
      |                              %lu
[ 12%] Building CXX object CMakeFiles/vcflib.dir/contrib/tabixpp/tabix.cpp.o
[ 13%] Linking CXX shared library libvcflib.so
[ 13%] Built target vcflib
[ 13%] Creating directories for 'ZIG-EXT'
[ 13%] No download step for 'ZIG-EXT'
[ 13%] No update step for 'ZIG-EXT'
[ 14%] No patch step for 'ZIG-EXT'
[ 15%] No configure step for 'ZIG-EXT'
[ 15%] Performing build step for 'ZIG-EXT'
ZIG PATH /soft/zig-x86_64-linux-0.16.0/bin:/soft/zig-0.15.2/bin/:/soft/gatk-4.6.2.0:/soft/nss_wrapper/bin:/soft/falco-1.3.0/bin:/soft/BBTools-39.81:/soft/gff3sort-1.0.0:/soft/seqtk-1.5/bin:/soft/vcftools-0.1.17/bin:/soft/bcftools-1.23.1/bin:/soft/samtools-1.23.1/bin:/soft/htslib-1.23.1/bin:/soft/libdeflate-1.25/bin:/soft/memusage/bin:/soft/cpanm/bin:/soft/cmake-4.3.2-linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
0.16.0
install
└─ install zig
   └─ compile lib zig Debug native 2 errors
./samples.zig:40:13: error: returning address of expired local variable 'list'
    return &list;
            ^~~~
./samples.zig:28:9: note: declared runtime-known here
    var list = ArrayList([] const u8){};
        ^~~~
./vcf.zig:285:32: error: missing struct field: items
    var vs = ArrayList(Variant){};
             ~~~~~~~~~~~~~~~~~~^~
./vcf.zig:285:32: note: missing struct field: capacity
/soft/zig-x86_64-linux-0.16.0/lib/std/array_list.zig:576:12: note: struct declared here
    return struct {
           ^~~~~~
referenced by:
    zig_create_multi_allelic: ./vcf.zig:275:50
    zig_create_multi_allelic: ./vcf.zig:274:1
    4 reference(s) hidden; use '-freference-trace=6' to see all references
error: 2 compilation errors
failed command: /soft/zig-x86_64-linux-0.16.0/bin/zig build-lib -fPIC -ODebug -Mroot=/soft/vcflib-1.0.15-src/src/zig/vcf.zig --cache-dir .zig-cache --global-cache-dir /soft/vcflib-1.0.15-src/src/zig --name zig -static --zig-lib-dir /soft/zig-x86_64-linux-0.16.0/lib/ --listen=-

Build Summary: 0/3 steps succeeded (1 failed)
install transitive failure
└─ install zig transitive failure
   └─ compile lib zig Debug native 2 errors

error: the following build command failed with exit code 1:
.zig-cache/o/365ff5e378a5bcba7bf0dd0ea58deb05/build /soft/zig-x86_64-linux-0.16.0/bin/zig /soft/zig-x86_64-linux-0.16.0/lib /soft/vcflib-1.0.15-src/src/zig .zig-cache /soft/vcflib-1.0.15-src/src/zig --seed 0x2b5ee9e2 -Zb5f32ec551e0d2fc
make[2]: *** [CMakeFiles/ZIG-EXT.dir/build.make:86: ZIG-EXT-prefix/src/ZIG-EXT-stamp/ZIG-EXT-build] Error 1
make[1]: *** [CMakeFiles/Makefile2:381: CMakeFiles/ZIG-EXT.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```
</details>

Everything is working with zig 0.15.2
